### ISSUE TITLE
 Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by MarioMunozMendez** [rbren/rss-parser#114]
Hello,

I'm triying to download feeds on my server. The url which i'm fetching is another app inside of my server. Both are with well https certificates and are working properly themselves. But when i try to fetch rss from one app to another it throws this error Hostname/IP doesn't match certificate's altnames. So i've been researching and i've seen many errors related to https request or axios but on this case rss-parser is using https underneath and i can't modify the options. Any suggestion please?

**Comment by bobby-brennan** [comment]
You can always retrieve the XML feed yourself, then use `parseString` instead of using `parseURL`.

It may also make sense to have an `httpOptions` passthrough, the same way we do for `xml2js`. Would happily accept a PR there.
