### ISSUE TITLE
No Use with Angular

### ISSUE THREAD

**Issue by Madtek** [rbren/rss-parser#120]
The Parser seems to have missing libs to get the data by its own.
 Code:

`import { Component, OnInit } from '@angular/core';
import * as Parser from "rss-parser";

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.scss']
})
export class BlogComponent implements OnInit {
  
  feed:any;

  constructor() { }

  ngOnInit() {
    let parser = new Parser();

    parser.parseURL('https://blog.my-site.de/feed/')
      .then((resp) => {
        this.feed = resp;

        console.log("blog feed", resp, this.feed);

      });
  }

}
`

On compile now there seems to some missing dependencies:
`WARNING in ./node_modules/xml2js/node_modules/sax/lib/sax.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\gregor\dev\projects
\my-site\git\my-site\node_modules\xml2js\node_modules\sax\lib'

ERROR in ./node_modules/rss-parser/lib/parser.js
Module not found: Error: Can't resolve 'http' in 'C:\Users\gregor\dev\projects\my-site\git\my-site\node_modules\rss-parser\lib'
ERROR in ./node_modules/rss-parser/lib/parser.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\gregor\dev\projects\
my-site\git\my-site\node_modules\rss-parser\lib'
ERROR in ./node_modules/xml2js/lib/parser.js
Module not found: Error: Can't resolve 'timers' in 'C:\Users\gregor\dev\projects
\my-site\git\my-site\node_modules\xml2js\lib'
i ?wdm?: Failed to compile.
`

NPM dont tell me any missing dependencies.

What and How do I need to add to make it run?

**Comment by tofra** [comment]
npm install stream

**Comment by Madtek** [comment]
The stream issue is gone after installation. 

But the missing "http*" problems in lib are still there. 
What do I miss?

**Comment by nonintanon** [comment]
@Madtek got the same issue. `timers` can be solved by `npm i timers`. no luck for `http` and `https` yet.

**Comment by tofra** [comment]
put this in ```package.json```
```
  "browser": {
    "http": false,
    "https": false
  },
```

**Comment by nonintanon** [comment]
@tofra thanks! the `http` and `https` errors are gone after adding your snippet. the build passed but got this error when running instead..

`Uncaught (in promise): TypeError: get is not a function at parser.js:76`

Any idea? Is it related to lazy loading in Angular?

**Comment by tofra** [comment]
Could be multiple things.. Try: ```npm install --save-dev @types/node```
If that doesn't solve it, check if you have ```@angular/http``` in package.json, if not use ```npm install @ionic-native/http```

**Comment by bobby-brennan** [comment]
You won't be able to use `parseURL` if you're setting `http: false` in package.json. You'll have to download the XML yourself and use `parseString`.

It's not quite idiomatic Angular, but you can also add `dist/rss-parser.min.js` using a `<script>` tag (rather than using `require('rss-parser')`). This comes bundled with AJAX versions of http/https.
