### ISSUE TITLE
Add Ethereum address to package.json

### ISSUE THREAD

**Issue by lastmjs** [rbren/rss-parser#124]
I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a cannonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have Ethereum addresses in their package.json files: https://sustainus.io

**Comment by rbren** [comment]
Thanks, but I'm not interested in donations :)
