### ISSUE TITLE
TypeError: feed is undefined in Firefox

### ISSUE THREAD

**Issue by jasonbety** [rbren/rss-parser#125]
Here's my code :

```javascript
/**
	 * Parse les infos du Json
	 * @param {string} categorieString
	 * @param {string} categorieArticle
	 */
	function parserJson(categorieString, categorieArticle)
	{
		parser.parseURL(urlBlogue+categorieArticle, function(err, feed)
		{
			feed.items.forEach(function(item, cle)
			{
				if (2 >=cle )
				{
					var html =
						'<div class="col-md-4 publication">' +
							'<div>' +
								'<h3>'+ item.title + '</h3>' +
								'<a href="'+item.link+'">' + getImage(item.content) + '</a>' + formaterString(item.content, categorieString) +
								'<p class="link">'+
									'<a href="'+item.link+'">' + '<span class="iconfont iconfont-arrow-right"></span>' + '</a>' +
								'</p>' +
							'</div>' +
						'</div>';
				}
				$('.' + categorieString + ' .row .col-md-10 .row').append(html);
			});
		});
	}
```

It works on Chrome and even on IE11 !!
but in the last version of Fifefox, I got this error : TypeError: feed is undefined

**Comment by tofra** [comment]
What does the console show you? And what is the value of `err`?

**Comment by jasonbety** [comment]
This is my console :

`err: TypeError: "NetworkError when attempting to fetch resource." publications.js:28:11
feed: undefined publications.js:29:11
err: TypeError: "NetworkError when attempting to fetch resource." publications.js:28:11
feed: undefined publications.js:29:11
err: TypeError: "NetworkError when attempting to fetch resource." publications.js:28:11
feed: undefined publications.js:29:11
TypeError: feed is undefined
3 publications.js:30:3
L’encodage de caractères d’un document en texte brut n’a pas été déclaré. Le document sera affiché avec des caractères incorrects pour certaines configurations de navigateur si le document contient des caractères en dehors de la plage US-ASCII. L’encodage de caractères du fichier doit être déclaré dans le protocole de transfert ou le fichier doit utiliser une marque d’ordre des octets (BOM) comme signature d’encodage.`

**Comment by tofra** [comment]
What is `urlBlogue+categorieArticle`?

Do you have a git repo so it's reproducible?

**Comment by jasonbety** [comment]
urlBlogue = https://blogue.som.ca/
categorieArticle = feed/atom/?cat=72

**Comment by jasonbety** [comment]
I found my problem. I forgot to add the const CORS_PROXY = "https://cors-anywhere.herokuapp.com/"
