### ISSUE TITLE
content:encoded + CDATA

### ISSUE THREAD

**Issue by Dastano** [rbren/rss-parser#131]
Hey, 

I try to parse this Feed: https://community.blackdesertonline.com/index.php?forums/patchnotes.61/index.rss

however, if I parse it as XML or RSS directly, I cannot access Content. Content is shown as:

 'content:encoded'

same as :

'dc:creator':

So access them with feed.content or feed['content:encoded'] do not work. Not sure if I do a mistake or if there is a parsing error.

Hope you can help me out :)

**Comment by rbren** [comment]
Can you share your code?

**Comment by Dastano** [comment]
Hey!

Thanks for take care :)

I just used the example Code:

`let Parser = require('rss-parser');
let parser = new Parser();

(async () => {

  let feed = await parser.parseURL('https://community.blackdesertonline.com/index.php?forums/patchnotes.61/index.rss');
  console.log(feed.title);

  feed.items.forEach(item => {
    console.log(item.title + ':' + item.link)
  });

})();`

**Comment by rbren** [comment]
I think you want `item.content` etc, not `feed.content`. Content is associated with individual items, not the feed.

**Comment by Dastano** [comment]
If you do:

feed.items.forEach(item => {
console.log(item.content)
})

It just return's undefined. I guess the XML Parser not parse it propperly, because I just tested the XML2JS and get the same result.

**Comment by Dastano** [comment]
got it working, by do : item['content:encoded']
