### ISSUE TITLE
Add options in parseURL such as rejectUnauthorized to bypass HTTPS issues.

### ISSUE THREAD

**Issue by jgui1129** [rbren/rss-parser#137]
Hi @rbren , thanks for this awesome library.
I would like to ask if it's ok to add options in the parseURL such as rejectUnauthorized to override some options there.

<img width="668" alt="Screen Shot 2019-10-23 at 7 25 39 PM" src="https://user-images.githubusercontent.com/29097518/67388385-1fab5880-f5cb-11e9-9355-68f88f9e812a.png">

I encountered an issue with some RSS with HTTPS saying "unable to verify the first certificate"
w/c was resolved by using adding NODE_TLS_REJECT_UNAUTHORIZED=0 in the .env, however it is not recommended and what they recommend is adding rejectUnauthorized in the get method (w/c i did in the code above)

Let me know your thought. 
I can also submit a PR if that's ok.
Thank you.

**Comment by rbren** [comment]
Thanks! We've talked in the past about adding a `requestOptions` passthrough, similar to what we do for `xml2js`: https://github.com/rbren/rss-parser#xml2js-passthrough

I'd definitely accept a PR to that effect.

**Comment by timqian** [comment]
I met the same issue today. Adding the passthrough in this PR https://github.com/rbren/rss-parser/pull/160
