### ISSUE TITLE
Cannot get custom fields to work for Listal RSS

### ISSUE THREAD

**Issue by rlorenzo** [rbren/rss-parser#141]
I cannot seem to get the custom fields to work for this RSS feed: https://www.listal.com/viewlist/movies/859/?rss=true

I created an repl.it to demo the code I am using:

https://repl.it/@rex2/RowdyBrilliantTransformations

The output just shows blank for rating.

I hope you can see what I am doing wrong here.

**Comment by rbren** [comment]
Looks like all the `<listal:rating>` tags in that RSS feed are empty.

**Comment by rlorenzo** [comment]
I feel like a dummy. I was pulling my hair out trying to figure it out because the rating shows up when I viewed the RSS feed, but turns out it is because I was logged in. Even though I set the RSS to public it still redacts information. I will try using the parser for a downloaded RSS file.
