### ISSUE TITLE
Question: is it possible to specify http request header?

### ISSUE THREAD

**Issue by etcware** [rbren/rss-parser#143]
For example:
{headers : {'Content-Type' : 'application/json; charset=UTF-8'}

**Comment by rbren** [comment]
Yup: https://github.com/rbren/rss-parser#headers

**Comment by drewgillen** [comment]
@rbren I am getting a Type error with the follow headers. 
```
    const parser = new Parser({
      headers: {'X-Requested-With': 'XMLHttpRequest'},
      customFields: {
        item: [['media:content', 'media']],
      },
    })
```

This is the error: 
```
Type '{ 'X-Requested-With': string; }' is not assignable to type 'Headers'.
  Object literal may only specify known properties, and ''X-Requested-With'' does not exist in type 'Headers'.ts(2322)
index.d.ts(21, 14): The expected type comes from property 'headers' which is declared here on type 'ParserOptions<{ [key: string]: any; }, { "media:content": any; } & { media: any; }>'
```

When I add the headers ```'X-Requested-With': 'XMLHttpRequest'``` to the ```Headers`` type inside of the rss-parser index.d.ts file the error goes away. This is the code:
```
  export interface Headers {
    readonly Accept?: string;
    readonly 'User-Agent'?: string;
    readonly 'X-Requested-With': 'XMLHttpRequest';
  }
```

Is there a way to extend the types of the ```Header``` object?

**Comment by rbren** [comment]
Hmm seems like we need to fix the type definition so it doesn't have a fixed set of keys. Happy to accept a PR here--I don't know typescript very well.

**Comment by drewgillen** [comment]
> Hmm seems like we need to fix the type definition so it doesn't have a fixed set of keys. Happy to accept a PR here--I don't know typescript very well.

Upon further inspection the ```Headers``` type is not declared in the source code of the library. You can either declare the ```Headers``` type inside of ```index.d.ts``` to accept all strings. Or update the ```parser.js``` file to accept an empty string as one of the ```DEFAULT_HEADERS```.

It looks like the ```Headers``` type gets generated upon package installation. 

 Here is the ```Headers``` type declaration fix to accept all strings inside the ```index.d.ts``` file:
 ```
   export interface Headers {
    readonly Accept?: string;
    readonly 'User-Agent'?: string;
    readonly [key: string]: string | undefined;
  }
```

OR 

Here is the fix to accept an empty string as a default header inside the ```parser.js``` file: 
```
const DEFAULT_HEADERS = {
  'User-Agent': 'rss-parser',
  'Accept': 'application/rss+xml',
  '': '',
}
```
 
 I have tested the first option and it does work. Let me know which option your prefer and I can create a PR. Thank you!
