### ISSUE TITLE
Status code 406

### ISSUE THREAD

**Issue by muratbasci** [rbren/rss-parser#147]
I'm trying to parse the RSS feed which is located at the following URL:
https://www.rttnews.com/RSS/MarketAnalysis.xml
but I'm getting status code 406.

In a previous question, you wrote a solution to add the following code;
const parser = new Parser ({
   headers: {
     Accept: 'application / rss + xml, application / xml',
   },
});
I added that but the problem did not change. What could be the reason?

**Comment by dragoonzx** [comment]
Same problem 👶

**Comment by rbren** [comment]
See https://github.com/rbren/rss-parser/issues/129
