### ISSUE TITLE
chang from req.setTimeout to straight setTimeout leaks timeouts

### ISSUE THREAD

**Issue by bjj** [rbren/rss-parser#149]
The commit 9858a9d which changes req.setTimeout to straight setTimeout leaks timeouts. It's not a problem that it eventually calls reject (because the promise ignores the late reject). The problem is that it keeps node from exiting because there are pending timeouts (which you can verify with the why-is-node-running module).

If parseURL wants to handle timeouts itself it needs to set the timeout first, capture the return value (timeout id), and clearTimeout(id) everywhere it resolves or rejects.

**Comment by rbren** [comment]
Good point! With a default timeout of 60s I can see how this would be annoying.

See https://github.com/rbren/rss-parser/pull/150 - any thoughts/concerns on that solution?

**Comment by bjj** [comment]
Looks good.
