### ISSUE TITLE
Encoding not working

### ISSUE THREAD

**Issue by Feuerhamster** [rbren/rss-parser#151]
I want to get a feed with special characters, but its not working.
Here is the feed: https://www.queer.de/rss/newsticker2.0.komplett.xml

The feed is in iso-8859-1 (Latin1) but chars like ä/ö/ü are displayed as �

**Comment by rbren** [comment]
NodeJS doesn't support the latin1 encoding out-of-the-box. We have avoided bundling in iconv, because it adds a lot of weight to the browser distribution.

I would suggest downloading the feed yourself, using `iconv` to convert the encoding, then using `rssParser.parseString`
