### ISSUE TITLE
Question: How to parse a local xml file ?

### ISSUE THREAD

**Issue by StartMeUpLille** [rbren/rss-parser#157]
Hi
I love this plugin ! 
As I need to carry out some tests to see how to use it, I was wondering how I could use a local xml file instead of fetching a url every time I run my functions.
So I have my rss.xml file stored in the same folder, how do I parse it ?
Should I use parseString or parseURL, and what about the path to my xml file ?

let feed = await parser.parseString('rss.xml'); 

Thanks if you can help me on this

**Comment by rbren** [comment]
Yes, you can use `fs` to read the file, then pass the contents of the file to `parseString`.

**Comment by StartMeUpLille** [comment]
Hi rben
Many thanks for pointing out to a solution.
