### ISSUE TITLE
rss-parser vs rss-to-json library

### ISSUE THREAD

**Issue by stokito** [rbren/rss-parser#163]
I found another library which also makes a mapping between RSS and JSON https://www.npmjs.com/package/rss-to-json
As far I understood the only difference is that it doesn't performs requests itself.
Can you please tell me if any other differences? Pros and cons. Maybe it worth to merge this two projects or reuse some code from them.

**Comment by rbren** [comment]
I'm not familiar with that library. The things I'd check for are:
* rss 1.0 and 2.0 support
* Atom support
* itunes support
* support for custom/non-standard fields
