### ISSUE TITLE
Wordpress CORS

### ISSUE THREAD

**Issue by stokito** [rbren/rss-parser#164]
I created a ticket for WP where asked them to enable CORS for feeds https://core.trac.wordpress.org/ticket/50441
I hope this may be interesting for you so maybe you can add some comments and thoughts on this.
Maybe you know better if it safe to enable CORS for feeds.

**Comment by rbren** [comment]
Thanks for the info! Yeah it should be safe to enable CORS for RSS, so long as it's not altering the feed based on any user sessions etc

Going to close this since it's unrelated to rss-parser though.
