### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by chaitragkashyap** [rbren/rss-parser#170]
I need to support in IE11. But it is failing for IE 11.  As soon as I initialize the let parser = new Parser(); The code fails to load.

**Comment by rbren** [comment]
Can you share some more information? What's the warning message?

Does IE11 support `let`?

**Comment by chaitragkashyap** [comment]
I tried to use this in aSharePoint SPFX webpart to display RSS feed. The
error message was "cannot load entry point from component" The error
disappeared if I comment the code for rss-parser. I ended up using react
fetch to make call to the rss feed.

Thanks

**Comment by rbren** [comment]
👍 glad you managed to solve it
