### ISSUE TITLE
authorization is not working in headers

### ISSUE THREAD

**Issue by amide-inc** [rbren/rss-parser#172]
const parser = new Parser({
   headers: {
       'Content-Type': 'application/json',
       '**Authorization' : 'Basic '+ Buffer.from('username:password').toString('base64')**
   },
   
   
});

**Comment by rbren** [comment]
What is the issue you're seeing specifically?

This likely doesn't have anything to do with rss-parser. You can try installing [http-debug](https://www.npmjs.com/package/http-debug) to see if the header is being set.
