### ISSUE TITLE
Adds TS types for customFields

### ISSUE THREAD

**Issue by JbIPS** [rbren/rss-parser#175]
Hi,

I'm experimenting with RSS in TypeScript and your lib is very intuitive!

One thing I'd like to upgrade is the `customFields` you pass to the constructor. Since in the TS types you authorize any key/value pair, there is no control anymore.

With the use of a generic type `Parser<FeedFields, ItemFields>`, the `parse` method could output an union of `Output` and `FeedFields`. Bonus, you could type the `CustomFields` to 
```typescript
export interface CustomFields<T,U> {
  readonly feed?: (keyof T)[],
  readonly item?: CustomFieldItem<U>[]  | CustomFieldItem<U>[][]
}
```
so it would throw a compile error if you make in case of a type:
```typescript
const parser = new Parser<{foo: string}, {bar: number}>({
  customFields: {
    feed: ['fooo']    <---- Error
    item: ['bar']
  }
});
```

I already made the changes on my local files so I could make a PR if your interested by those changes.

Thank you for the lib!

**Comment by rbren** [comment]
Thanks for the feedback!

In this scenario, would
```js
const parser = new Parser({
  customFields: {
    feed: ['fooo'],
    item: ['bar']
  }
});
```
still be valid? I'd like to make sure the TS remains mostly backward-compatible

**Comment by JbIPS** [comment]
We could make the generic optional 
```typescript
interface Parser<T = {[key: string]: any}, U = {[key: string]: any}>
```
This way, if you don't provide a type, you won't have completion nor control but anything will be authorized, as before.
