### ISSUE TITLE
XML RSS 2 site keeps timing out but loads fine in a browser

### ISSUE THREAD

**Issue by Alchete** [rbren/rss-parser#188]
Many thanks for the library.  rss-parser v3.10

However, this site keeps giving me a timeout error, yet in a browser the XML loads immediately.  Is there something in their RSS that's not supported?

http://ir.tesla.com/rss/news-releases.xml - Error: Request timed out after 10000ms

**Comment by yPhil-gh** [comment]
I tried this feed in various readers, _none_ could read it, not even manage a proper error, there _really_ seem to be [something very wrong with it](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fir.tesla.com%2Frss%2Fnews-releases.xml).

**Comment by Alchete** [comment]
I forgot all about this issue. :)  Thanks for trying it.  I believe since December that they actually changed their RSS address.  Marking closed.
