### ISSUE TITLE
404 error on youtube rss

### ISSUE THREAD

**Issue by barisusakli** [rbren/rss-parser#206]
Url https://www.youtube.com/feeds/videos.xml?channel_id=UC3rtMH-98Lct2uJaK8YcxpQ

Works fine when loading in browser, but using this module throws 404 any idea why?

```
feed.getItems = async function (feedUrl, entriesToPull) {
	entriesToPull = parseInt(entriesToPull, 10) || 4;
	feedUrl = feedUrl + '?t=' + Date.now();

	const parser = new Parser();
	const feed = await parser.parseURL(feedUrl);
	return feed.items;
};
```

**Comment by xtradev** [comment]
Now it does not work in browser either.

**Comment by rbren** [comment]
Probably some kind of user-agent sniffing. I'd try using the CORS proxy in the README.
