### ISSUE TITLE
Parsing fields with the same name

### ISSUE THREAD

**Issue by sjensen19** [rbren/rss-parser#218]
Hi there,

I am trying to parse a RSS feed with multiple fields that have the same name.
This is the API I am using: https://api.nevobo.nl/export/poule/regio-zuid/JC1A1/stand.rss

There are multiple fields with the name ```stand:ranking```. If I add ```stand:ranking``` to the custom fields list like this:
```js
let parser = new Parser({customFields: {
        feed: ["stand:ranking"]
      }
});
```
It only returns the first item, not the other 4 items.

How would I be able to parse them all?

**Comment by klize** [comment]
@sjensen19 sorry for lately asking the result, how did you solve it ?  I have the same issue while parsing feed.

**Comment by sjensen19** [comment]
Hi @klize,

To be really honest, didn't really find a solution. Was hoping the creator of the repo would know the answer, but he seems quite inactive.

I closed the issue because the creator of the API I was using released a newer version of the api with a json feed instead of a rss feed, therefore not needing the solution anymore.

Hope this helps!
