### ISSUE TITLE
Not able to parse RSS Url. Error: Unencoded < Line: 0 Column: 2

### ISSUE THREAD

**Issue by karnshah8890** [rbren/rss-parser#219]
I am using below URL:
https://www.fotball.no/footballapi/PublicMethods/Rssfeed?d=1&kw=3

**rss-parser gives me error:**
Error: Unencoded <
Line: 0
Column: 2

1) What is the issue with it? 
2) Is it related to UTF-16?
3) How can I support UTF-16?

**Comment by karnshah8890** [comment]
@rbren can you help in this?

**Comment by rbren** [comment]
It's either an encoding issue or the feed is malformed.

You can try downloading it yourself with the request, axios, or http library, decoding it, and then using `parseString` instead of `parseURL`
