### ISSUE TITLE
Explain custom fields in TypeScript sample.

### ISSUE THREAD

**Issue by danielniccoli** [rbren/rss-parser#231]
I'm trying to understand the following statement in the TypeScript sample code (see below) of the README:

>  console.log(feed.title); // feed will have a `foo` property, type as a string

Looking at the object, there is no `foo` property. `feed.title.foo` is `undefined`. Same with `feed.item[0].bar`. It's not evident what the CustomFeed and CustomItem objects are doing.

Sample code of the README for your convenience:
```ts
import Parser from 'rss-parser';

type CustomFeed = {foo: string};
type CustomItem = {bar: number};

const parser: Parser<CustomFeed, CustomItem> = new Parser({
  customFields: {
    feed: ['foo', 'baz'],
    //            ^ will error because `baz` is not a key of CustomFeed
    item: ['bar']
  }
});

(async () => {

  const feed = await parser.parseURL('https://www.reddit.com/.rss');
  console.log(feed.title); // feed will have a `foo` property, type as a string

  feed.items.forEach(item => {
    console.log(item.title + ':' + item.link) // item will have a `bar` property type as a number
  });
})();
```

**Comment by superb-owl** [comment]
customFields comes in handy if there's a non-standard field available in the RSS feed you're trying to parse.

For example, see [this test case](https://github.com/rbren/rss-parser/blob/e2e2f4d03a74811fd4dc624381b0f336bcdde962/test/parser.js#L131) which parses [this xml](https://github.com/rbren/rss-parser/blob/e2e2f4d03a74811fd4dc624381b0f336bcdde962/test/input/customfields.rss)

**Comment by rbren** [comment]
customFields is helpful if there are XML attributes available in the RSS which are non-standard RSS fields.

Check out [this test case](https://github.com/rbren/rss-parser/blob/e2e2f4d03a74811fd4dc624381b0f336bcdde962/test/parser.js#L131) which parses [this XML](https://github.com/rbren/rss-parser/blob/master/test/input/customfields.rss)
