### ISSUE TITLE
Socket remains open after a timeout

### ISSUE THREAD

**Issue by alexfernandez** [rbren/rss-parser#238]
Node v18.12.1, rss-parser@3.12.0. I am scraping a number of RSS feeds using `rss-parser`. A [Nasdaq feed](https://www.nasdaq.com/feed/rssoutbound?category=Commodities) is invariably giving a timeout after 10 seconds, which is the configured time:

    Could not read https://www.nasdaq.com/feed/rssoutbound?category=Commodities: Request timed out after 10000ms

The feed can be read without issues on a browser so I guess it is limited by user-agent on the server side. Anyway, my program does not terminate properly, and keeps the process open after everything else has been closed. Running it with [wtfnode](https://www.npmjs.com/package/wtfnode) yields the following information:

```
^C[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 2 (tty) (stdio)
  - fd 1 (tty) (stdio)
- Sockets:
  - 192.168.1.5:41910 -> 23.214.214.41:443
```

As it happens, 23.214.214.41 is (not coincidentally) the IP address of the Nasdaq Akamai endpoint:

```
 $ ping www.nasdaq.com
PING e6982.dsca.akamaiedge.net (23.214.214.41) 56(84) bytes of data.
```

It appears that `rss-parser` is not closing the socket properly after a timeout. Any ideas?

**Comment by goldsrc** [comment]
As a workaround try to fetch the xml yourself with either node's built-in fetch, axios, etc.
I made a PR trying to fix this issue (#264)
