### ISSUE TITLE
ParseURL fails with ERR_ADDRESS_UNREACHABLE in Android Emulator using Ionic/Capacitor in Android

### ISSUE THREAD

**Issue by dchase-sir** [rbren/rss-parser#252]
Works in the browser, but once I sync to Android and run it, the ParseURL can't seem to access the public RSS feed. The mobile app can access the Internet no problem, it's just through ParseURL. Gets ERR_ADDRESS_UNREACHABLE.

**Comment by dchase-sir** [comment]
Ok I noticed if I add the Cors Proxy from the example it works - I don't really understand why the error would be ERR_ADDRESS_UNREACHABLE for CORS, but at least I know it's CORS. Any tips, the rest of the app can access URL's just fine.

**Comment by rbren** [comment]
I would try downloading the URL using `fetch` or another HTTP library, then using `parseString`. That might give you more debug info. This doesn't seem like an rss-parser issue though
