### ISSUE TITLE
this.removeAllListener is not a function

### ISSUE THREAD

**Issue by alapaches** [rbren/rss-parser#258]
Hello,

I ran into a probleme whom I an't find any solutions for now.

What I've done so far is initialized a new Parser but I'm getting this annoying error : this.removeAllListener is not a function

Look into my code this is what I did so far (Using Nuxt 3.7.4 and Vue 3.3.4) : 

```javascript
import Parser  from 'rss-parser'
let rssParser = new Parser()
```

Do you have any ideas ?

**Comment by alapaches** [comment]
It seems mandatory to include "timers" in order for this function to work. Creating a MR asap

**Comment by Aganivi** [comment]
Hello, I had the same problem. How to solve it?

**Comment by andrei-hudovich** [comment]
> Hello, I had the same problem. How to solve it?

It looks like the `events` package is missing, installing it as a dependency works for now.

See this PR: https://github.com/rbren/rss-parser/pull/259
