### ISSUE TITLE
Can I access returned headers?

### ISSUE THREAD

**Issue by ComputerCarl** [rbren/rss-parser#56]
Hello.. thank you for the great repo!

I am trying to access the `Last-Modified` and `ETag` headers to perform a conditional get.
Are those available or would I have to perform a preliminary check?

More info here;
https://fishbowl.pastiche.org/2002/10/21/http_conditional_get_for_rss_hackers/

**Comment by bobby-brennan** [comment]
Hi Carl,

I would suggest issuing the HTTP request yourself, then passing the result to `parseString`.

You could also modify the code to add the response headers to the returned object. Or there might be a clever way to handle the conditional GET inside the library. Happy to accept a PR if you go that route.

**Comment by bobby-brennan** [comment]
Keeping this open - we should implement an `ifModifiedSince` option

**Comment by ComputerCarl** [comment]
so sorry I let this slip! Thank you for the advice.. it worked well.. here's kinda what I did (modified, not tested);
````js
const axios = require('axios');
let Parser = require('rss-parser');
let parser = new Parser();
module.exports = async function parseRss(params) {
  const { lastModified, url } = params; // from db record of RSS parse

  let headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0',
    'If-Modified-Since':  lastModified) || null
  };

  let result = await axios({
    url,
    headers,
    method: 'get',
  })
    .then(result => result)
    .catch(err => ({ error: '304/404', url }));

  if (result.error) return result.error;

  let xml = result.data;
  let rssParsed;
  try {
    rssParsed = await parser.parseString(xml);
  } catch (err) {
    debug('error in `rss-parser`');
    return false;
  }

  rssParsed.lastModified = result.headers['last-modified'];
  rssParsed.etag = result.headers['etag'];

  if (rssParsed.error) return rssParsed.error;

return rssParsed;

````
